export const errors = {
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    MISSING_FIELDS: "MISSING_FIELDS",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    OTP_SENT_PHONE: "OTP_SENT_PHONE",
    OTP_EXPIRED: "OTP_EXPIRED",


}